---
- name: Create a temporary file
  tempfile:
    state: file
  register: tempfile_pullsecret

- name: Copy pull secret to file
  copy:
    content: "{{ pull_secret }}"
    dest: "{{ tempfile_pullsecret.path }}"

- name: Create cluster and download ISO
  block:
    - name: Create new AI cluster
      shell: "aicli create cluster  {{ cluster_name }}-day2"

    - name: Generate the ISO for the cluster
      shell: "aicli create iso -P ssh_public_key='{{ ssh_public_key }}' {{ cluster_name }}-day2"

    - name: And download it
      shell: "aicli download iso {{ cluster_name }}-day2 -p {{ ai_iso_path }}"

    - name: Copy AI ISO to HTTP Server
      shell: "cp {{ ai_iso_path }}/{{ cluster_name }}-day2.iso {{ http_server_path }}"
  environment:
    AI_URL: "{{ ai_url }}"

